name: 'Continuous Integration'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: 'Continuous Integration'
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: sugaming
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3

      - name: Install dependencies
        run: yarn install

      - name: Check formatting
        run: yarn nx format:check

      - name: Check linting
        run: yarn nx affected -t lint --parallel

      - name: Test
        run: yarn nx affected -t test --parallel --configuration=ci

      - name: Build
        run: yarn nx affected -t build --parallel

      - name: Get environment file
        run: |
          curl -H "Authorization: token ${TOKEN}" https://raw.githubusercontent.com/fss-fmi/secrets/main/sugaming/.env.development > .env
          curl -H "Authorization: token ${TOKEN}" https://raw.githubusercontent.com/fss-fmi/secrets/main/sugaming/apps/sugaming-api/.env.development > ./apps/sugaming-api/.env
          curl -H "Authorization: token ${TOKEN}" https://raw.githubusercontent.com/fss-fmi/secrets/main/sugaming/apps/sugaming-site/.env.development > ./apps/sugaming-api/.env
          curl -H "Authorization: token ${TOKEN}" https://raw.githubusercontent.com/fss-fmi/secrets/main/sugaming/apps/sugaming-admin/.env.development > ./apps/sugaming-admin/.env
        env:
          TOKEN: ${{ secrets.FSS_FMI_GITHUB_TOKEN }}

      - name: E2E
        run: |
          yarn prisma migrate dev
          yarn nx affected -t e2e --parallel=false
