name: 'Release'

on:
  push:
    tags:
      - v*


jobs:
  vercel-deploy:
    name: 'Deploy ${{ matrix.NAME }} to Vercel'
    runs-on: ubuntu-latest

    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets[matrix.PROJECT_ID_VARIABLE] }}

    strategy:
      matrix:
        include:
          - NAME: 'sugaming-api'
            PROJECT_ID_VARIABLE: 'VERCEL_PROJECT_API_ID'
          - NAME: 'sugaming-site'
            PROJECT_ID_VARIABLE: 'VERCEL_PROJECT_SITE_ID'
          - NAME: 'sugaming-admin'
            PROJECT_ID_VARIABLE: 'VERCEL_PROJECT_ADMIN_ID'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: yarn global add vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_API_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_API_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_API_TOKEN }}
