name: 'Release'

on:
  push:
    tags:
      - v*


jobs:
  vercel-deploy:
    name: 'Deploy ${{ matrix.NAME }} to Vercel'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - NAME: 'sugaming-api'
            PROJECT_ID_VARIABLE: 'VERCEL_PROJECT_API_ID'
          - NAME: 'sugaming-site'
            PROJECT_ID_VARIABLE: 'VERCEL_PROJECT_SITE_ID'
          - NAME: 'sugaming-admin'
            PROJECT_ID_VARIABLE: 'VERCEL_PROJECT_ADMIN_ID'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to Vercel
        id: deploy
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: "UmPPRfc8536Xu2pgURZ7KZnW"
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets[matrix.PROJECT_ID_VARIABLE] }}
          vercel-args: '--prod'
          github-comment: false

      - name: Output Preview URL
        id: output-preview-url
        uses: cloudposse/github-action-matrix-outputs-write@main
        with:
          matrix-step-name: ${{ github.job }}
          matrix-key: ${{ matrix.NAME }}
          outputs: |-
            preview-url: ${{ steps.deploy.outputs.preview-url }}


  read-preview-urls:
    name: "Read Preview URLs"
    runs-on: ubuntu-latest
    needs: vercel-deploy

    steps:
      - uses: cloudposse/github-action-matrix-outputs-read@main
        id: read
        with:
          matrix-step-name: vercel-deploy

    outputs:
      result: "${{ steps.read.outputs.result }}"


  create-release:
    name: "Create Release"
    runs-on: ubuntu-latest
    needs: read-preview-urls
    permissions:
      contents: write

    steps:
      - uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          body: |-
            ## Environments
            **sugaming-api**: ${{ fromJson(needs.read-preview-urls.outputs.result).preview-url.sugaming-api }}
            **sugaming-site**: ${{ fromJson(needs.read-preview-urls.outputs.result).preview-url.sugaming-site }}
            **sugaming-admin**: ${{ fromJson(needs.read-preview-urls.outputs.result).preview-url.sugaming-admin }}
