name: 'Release'

on:
  push:
    tags:
      - v*


jobs:
  vercel-deploy:
    name: 'Deploy ${{ matrix.NAME }} to Vercel'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - NAME: 'sugaming-api'
            PROJECT_ID_VARIABLE: 'VERCEL_PROJECT_API_ID'
          - NAME: 'sugaming-site'
            PROJECT_ID_VARIABLE: 'VERCEL_PROJECT_SITE_ID'
          - NAME: 'sugaming-admin'
            PROJECT_ID_VARIABLE: 'VERCEL_PROJECT_ADMIN_ID'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to Vercel
        id: deploy
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_API_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets[matrix.PROJECT_ID_VARIABLE] }}
          vercel-args: '--prod'
          github-comment: false
